version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  
  adminer:
    container_name: adminer
    image: adminer
    ports: 
      - "9001:8080"

  redis:
    container_name: redis
    image: redis
    ports: 
      - "6379:6379"
  
  rebrow:
    container_name: rebrow
    image: marian/rebrow
    ports: 
      - "9002:5001"